version: '3.4'

services:
HomeAssistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: Homeassistant
    hostname: home-server
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${DOCKER_TZ}
    ports:
      - 8123:8123
    network_mode: host
    volumes:
      - ${DOCKER_PATCH}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_PATCH}/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    devices:
      - /dev/ttyACM0
    restart: always
    