version: '3.4'

services:
  deconz:
    image: deconzcommunity/deconz:latest
    container_name: deconz
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_PATCH}/deconz:/opt/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - TZ=${DOCKER_TZ}
      - DECONZ_DEVICE=/dev/ttyACM0
      - DECONZ_WEB_PORT=82
      - DECONZ_WS_PORT=445
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_VNC_PASSWORD=${DOCKER_DECONZ_VNC_PASSWORD}
    ports:
      - 445:443
      - 82:82
      
