version: "2.1"

services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=${DOCKER_TZ}
      - RUN_OPTS=run options here #optional
    volumes:
      - ${DOCKER_PATCH}/jackett:/config
      - ${DOCKER_PATCH_MEDIA_DOWNLOAD}:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    